# Generated by Django 4.0.3 on 2022-03-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to='profile_pics/')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
